# Generated by Django 4.2.2 on 2023-06-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cookplanner_app",
            "0004_taste_rename_receiptingredients_recipeingredients_and_more",
        ),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="favorites",
            field=models.ManyToManyField(
                related_name="favorites", to="cookplanner_app.recipe"
            ),
        ),
    ]
