# Generated by Django 4.2.2 on 2023-06-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cookplanner_app", "0003_alter_receiptingredients_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name="ReceiptIngredients",
            new_name="RecipeIngredients",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="taste",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="taste",
                to="cookplanner_app.taste",
            ),
        ),
    ]
