# Generated by Django 4.2.3 on 2023-07-11 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookplanner_app', '0006_mealplan_meal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan', to='cookplanner_app.mealplan'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='cookplanner_app.recipe'),
        ),
    ]
