# Generated by Django 4.2.2 on 2023-07-16 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cookplanner_app", "0008_recipeingredients_unit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="url_recipe",
            new_name="process",
        ),
    ]
