# Generated by Django 4.2.2 on 2023-07-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookplanner_app", "0009_rename_url_recipe_recipe_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="validation",
            field=models.BooleanField(default=False),
        ),
    ]
