# Generated by Django 4.2.2 on 2023-07-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookplanner_app", "0010_recipe_validation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredients",
            name="amount",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
