# Generated by Django 4.2.2 on 2023-08-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookplanner_app', '0014_alter_recipe_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calorie',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
